version: '3.8'

services:
  translation-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Optional: Mount cache directory to persist downloaded models
      - model-cache:/home/appuser/.cache/huggingface
    user: appuser
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/docs')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Test service for running tests
  test:
    build: .
    environment:
      - PYTHONPATH=/app
      - TRANSLATION_LAZY_LOADING=true  # Use lazy loading for faster test startup
    volumes:
      - model-cache:/home/appuser/.cache/huggingface
    user: appuser
    command: python -m pytest -v
    profiles:
      - test

volumes:
  model-cache:
    driver: local